<a href="https://colab.research.google.com/github/DharaCS23181/Skincare_Product_Prediction/blob/main/Dataset_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import tensorflow as tf

from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [4]:
import pandas as pd
newdf = pd.read_csv("/content/drive/MyDrive/ML/Skin Care Product Recommendation System.csv")

In [5]:
newdf.head()

,product_href,product_name,product_type,brand,notable_effects,skintype,price,description,picture_src
0,https://www.beautyhaul.com/product/detail/bubb...,ACWELL Bubble Free PH Balancing Cleanser,Face Wash,ACWELL,"Acne-Free, Pore-Care, Brightening, Anti-Aging",Oily,Rp 209.000,Mengangkat kotoran dan menghapus makeup dalam ...,https://www.beautyhaul.com/assets/uploads/prod...
1,https://www.sociolla.com/face-wash/62452-ph-ba...,ACWELL pH Balancing Soothing Cleansing Foam,Face Wash,ACWELL,"Soothing, Balancing","Normal, Dry, Combination",Rp 181.800,Membersihkan dan menenangkan kulit sensitif de...,https://images.soco.id/8f08ced0-344d-41f4-a15e...
2,https://www.sociolla.com/toner/15871-licorice-...,Acwell Licorice pH Balancing Cleansing Toner,Toner,ACWELL,"Soothing, Balancing","Normal, Dry, Oily, Combination, Sensitive",Rp 149.000,"Mengangkat sisa kotoran, debu, dan make up sek...","https://www.soco.id/cdn-cgi/image/w=73,format=..."
3,https://www.beautyhaul.com/product/detail/aqua...,ACWELL Aquaseal Soothing Tonic,Toner,ACWELL,"Acne-Free, Pore-Care, Brightening, Anti-Aging",Oily,Rp 290.000,Pre-essence yang diformulasikan dengan ekstrak...,https://www.beautyhaul.com/assets/uploads/prod...
4,https://www.sociolla.com/essence/38023-licoric...,Licorice pH Balancing Essence Mist,Toner,ACWELL,"Brightening, Soothing","Normal, Dry",Rp 194.650,Essens mist dengan kelembapan tinggi yang memb...,"https://www.sociolla.com/cdn-cgi/image/w=425,f..."

In [6]:
skindf = pd.read_csv("/content/drive/MyDrive/ML/skintype.csv")

In [7]:
skindf.head()

,Age,Gender,Hydration_Level,Oil_Level,Sensitivity,Humidity,Temperature,Skin_Type
0,36,Male,Low,Low,High,31.9,10.1,Dry
1,36,Female,High,Low,High,30.1,20.5,Combination
2,34,Female,High,Medium,Low,53.0,19.5,Normal
3,51,Male,Medium,High,Low,57.3,22.7,Oily
4,36,Male,High,Medium,Medium,64.4,24.0,Normal

In [8]:
newdf = newdf.drop(columns=['product_href', 'price', 'description'])

In [9]:
newdf.columns

Index(['product_name', 'product_type', 'brand', 'notable_effects', 'skintype',
       'picture_src'],
      dtype='object')

In [10]:
skindf = skindf.drop(columns=['Hydration_Level','Oil_Level','Sensitivity'])

In [11]:
skindf.columns

Index(['Age', 'Gender', 'Humidity', 'Temperature', 'Skin_Type'], dtype='object')

In [12]:
skindf = skindf.drop(columns=['Gender'])

In [13]:
newdf.columns

Index(['product_name', 'product_type', 'brand', 'notable_effects', 'skintype',
       'picture_src'],
      dtype='object')

In [14]:
newdf['notable_effects'].unique()

array(['Acne-Free, Pore-Care, Brightening, Anti-Aging',
       'Soothing, Balancing', 'Brightening, Soothing',
       'Moisturizing, Brightening, Anti-Aging',
       'Moisturizing, Brightening', 'Hydrating, Balancing, Moisturizing',
       'Pore-Care, Brightening, Anti-Aging', 'Anti-Aging',
       'Brightening, Anti-Aging, UV-Protection',
       'Anti-Aging, UV-Protection', 'Balancing, Oil-Control, Pore-Care',
       'Hydrating, Moisturizing', 'Hydrating, Soothing',
       'UV-Protection, No-Whitecast', 'Skin-Barrier, UV-Protection',
       'Moisturizing, Pore-Care', 'Hydrating, Refreshing',
       'Hydrating, Pore-Care', 'Moisturizing, Refreshing, Oil-Control',
       'Moisturizing, UV-Protection', 'Hydrating, UV-Protection',
       'Acne-Free, Oil-Control, Anti-Aging', 'Hydrating, Pore-Care ',
       'Moisturizing', 'Moisturizing, Refreshing',
       'Moisturizing, Brightening, Black-Spot',
       'Soothing, Brightening, Black-Spot',
       'Soothing, Balancing, Brightening',
       'Acne-Free, Oil-Control, Pore-Care',
       'Moisturizing, Anti-Aging, Skin-Barrier', 'Soothing, Brightening',
       'Hydrating, Anti-Aging, Skin-Barrier', 'Brightening, Anti-Aging',
       'Brightening, Black-Spot, Anti-Aging, Skin-Barrier',
       'Acne-Free, Oil-Control, Brightening, Skin-Barrier',
       'Soothing, UV-Protection',
       'Hydrating, Acne-Free, Brightening, Black-Spot',
       'Acne-Free, Pore-Care, Anti-Aging',
       'Soothing, Acne-Free, Oil-Control', 'Soothing, Moisturizing',
       'Moisturizing, Brightening, Black-Spot, Anti-Aging',
       'UV-Protection', 'Moisturizing, Acne-Free',
       'Hydrating, Moisturizing, Refreshing',
       'Brightening, UV-Protection',
       'Hydrating, Moisturizing, UV-Protection',
       'Hydrating, Balancing, Skin-Barrier',
       'Acne-Free, Brightening, Anti-Aging', 'Acne-Free, Anti-Aging',
       'Moisturizing, Brightening, Skin-Barrier',
       'Soothing, Moisturizing, Brightening, Black-Spot',
       'Soothing, Acne-Free, Pore-Care',
       'Acne-Free, Oil-Control, Black-Spot', 'Refreshing, Pore-Care',
       'Soothing, Refreshing', 'Acne-Free, Pore-Care, Black-Spot',
       'Acne-Free, Skin-Barrier', 'Oil-Control, Pore-Care, Skin-Barrier',
       'Moisturizing, UV-Protection, No-Whitecast',
       'Pore-Care, Skin-Barrier, UV-Protection', 'Soothing, Skin-Barrier',
       'Brightening, Skin-Barrier', 'Hydrating, Soothing, Acne-Free',
       'Hydrating, Pore-Care, Brightening',
       'Soothing, Balancing, Pore-Care',
       'Pore-Care,  Brightening, Anti-Aging',
       'Acne-Free, Brightening, Black-Spot',
       'Moisturizing, Brightening, UV-Protection',
       'Acne-Free, Oil-Control', 'Acne-Free, UV-Protection',
       'Moisturizing, Acne-Free, Oil-Control',
       'Balancing, Acne-Free, Pore-Care',
       'Soothing, Moisturizing, UV-Protection',
       'Balancing, Moisturizing, Anti-Aging',
       'Balancing, Pore-Care, Brightening', 'Oil-Control, Pore-Care',
       'Pore-Care, Brightening', 'Acne-Free, Pore-Care, Skin-Barrier',
       'Moisturizing, Acne-Free, Skin-Barrier',
       'Acne-Free, Oil-Control, Skin-Barrier',
       'Balancing, Moisturizing, Oil-Control\n',
       'Acne-Free, Brightening, Pore-Care', 'Acne-Free, Brightening',
       'Brightening, Black-Spot, Anti-Aging',
       'Soothing, Moisturizing, Anti-Aging',
       'Hydrating, Brightening, Black-Spot',
       'Hydrating, Balancing, Oil-Control, Brightening',
       'Hydrating, Oil-Control', 'Acne-Free, Oil-control, Pore-Care',
       'Hydrating, Pore-Care, Skin-Barrier',
       'Brightening, UV-Protection ',
       'Acne-Free, Moisturizing, Oil-Control, Pore-Care',
       'Hydrating, Moisturizing, Pore-Care',
       'Moisturizing, Oil-Control, Pore-Care',
       'Moisturizing, Acne-Free, Anti-Aging',
       'Moisturizing, Skin-Barrier', 'Pore-Care, Skin-Barrier ',
       'Anti-Aging, Skin-Barrier, UV-Protection, No-Whitecast',
       'Soothing, Moisturizing, Skin-Barrier',
       'Soothing, Moisturizing, Black-Spot',
       'Refreshing, Moisturizing, Brightening, Skin-Barrier',
       'Moisturizing, Acne-Free, Black-Spot',
       'Soothing, Acne-Free, Moisturizing',
       'Soothing, Brightening, Acne-Spot',
       'Hydrating, Moisturizing, Acne-Free, Pore-Care', 'Moisturizing ',
       'Hydrating, Acne-Free, Oil-Control',
       'Hydrating, Moisturizing, Acne-Free, Oil-Control, Pore-Care',
       'Acne-Free, Oil-Control, Pore-Care, Brightening',
       'Hydrating, Brightening', 'Moisturizing, Oil-Control',
       'Brightening, Black-Spot, UV-Protection',
       'Moisturizing, Anti-Aging', 'Hydrating, Soothing, Brightening',
       'Soothing, Balancing, Acne-Free',
       'Hydrating, Oil-Control, Pore-Care',
       'Soothing, Acne-Free, Skin-Barrier',
       'Hydrating, Moisturizing, Skin-Barrier',
       'Hydrating, Moisturizing, Anti-Aging',
       'Soothing, Moisturizing, Acne-Free',
       'Soothing, Brightening, UV-Protection',
       'Acne-Free, Oil-Control, Black-Spot, Skin-Barrier',
       'Soothing, Refreshing, Oil-Control', 'Pore-Care, Skin-Barrier',
       'Hydrating, Pore-Care, Oil-Control', 'Balancing, Pore-Care',
       'Pore-Care, Anti-Aging', 'Hydrating, Balancing',
       'Balancing, Moisturizing', 'Soothing, Acne-Free',
       'UV-Protection, No-Whitecast ',
       'Pore-Care, UV-Protection, No-Whitecast ',
       'Refreshing, Skin-Barrier', 'Soothing, Balancing, Oil-Control',
       'Hydrating, Soothing ', 'Brightening, Black-Spot, Skin-Barrier',
       'Soothing, Anti-Aging, Skin-Barrier',
       'Balancing, Brightening, Skin-Barrier',
       'Pore-Care, UV-Protection, No-Whitecast', 'Pore-Care, Black-Spot',
       'Soothing, Oil-Control, Pore-Care', 'Refreshing, Oil-Control',
       'Hydrating, Acne-Free, Pore-Care',
       'Hydrating, Soothing, Moisturizing',
       'Moisturizing, Acne-Free, Brightening',
       'Hydrating, Moisturizing, Oil-Control',
       'Moisturizing, Pore-Care, Brightening', 'Acne-Free, Pore-Care',
       'Hydrating, Acne-Free, Brightening ',
       'Soothing, Acne-Free, Oil-Control, Pore-Care',
       'Refreshing, Acne-Free'], dtype=object)

In [15]:
newdf['notable_effects'] = (
    newdf['notable_effects']
    .str.lower()
    .str.replace('\n','')
    .str.strip()
)

In [16]:
newdf['notable_effects'] = newdf['notable_effects'].str.split(',')

In [17]:
newdf['notable_effects'] = newdf['notable_effects'].apply(
    lambda x: [i.strip() for i in x]
)

In [18]:
effects = set()

for row in newdf['notable_effects']:
    effects.update(row)

print(sorted(effects))

['acne-free', 'acne-spot', 'anti-aging', 'balancing', 'black-spot', 'brightening', 'hydrating', 'moisturizing', 'no-whitecast', 'oil-control', 'pore-care', 'refreshing', 'skin-barrier', 'soothing', 'uv-protection']

In [19]:
newdf.head()

,product_name,product_type,brand,notable_effects,skintype,picture_src
0,ACWELL Bubble Free PH Balancing Cleanser,Face Wash,ACWELL,"[acne-free, pore-care, brightening, anti-aging]",Oily,https://www.beautyhaul.com/assets/uploads/prod...
1,ACWELL pH Balancing Soothing Cleansing Foam,Face Wash,ACWELL,"[soothing, balancing]","Normal, Dry, Combination",https://images.soco.id/8f08ced0-344d-41f4-a15e...
2,Acwell Licorice pH Balancing Cleansing Toner,Toner,ACWELL,"[soothing, balancing]","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=..."
3,ACWELL Aquaseal Soothing Tonic,Toner,ACWELL,"[acne-free, pore-care, brightening, anti-aging]",Oily,https://www.beautyhaul.com/assets/uploads/prod...
4,Licorice pH Balancing Essence Mist,Toner,ACWELL,"[brightening, soothing]","Normal, Dry","https://www.sociolla.com/cdn-cgi/image/w=425,f..."

In [20]:
effect_condition_map = {
'acne-free' : 'acne',
'acne-spot' : 'acne',

'anti-aging' : 'wrinkles',

'balancing' : 'skin imbalance',

'black-spot' : 'pigmentation',

'brightening' : 'pigmentation',

'hydrating' : 'dry and dehydrated skin',
'moisturizing' : 'dry and dehydrated skin',

'oil-control' : 'oily skin',

'pore-care' : 'enlarged pores',

'skin-barrier' : 'impaired skin barrier',

'soothing' : 'redness',

'refreshing' : 'dull skin',

'uv-protection' : 'sun damage',
'no-whitecast' : 'sun protection'
}

In [21]:
def map_condition(effects):

    conditions = []

    for e in effects:
        if e in effect_condition_map:
            conditions.append(effect_condition_map[e])

    return list(set(conditions))

newdf['skin_condition'] = newdf['notable_effects'].apply(map_condition)

In [22]:
newdf[['notable_effects','skin_condition']].head()

,notable_effects,skin_condition
0,"[acne-free, pore-care, brightening, anti-aging]","[wrinkles, pigmentation, acne, enlarged pores]"
1,"[soothing, balancing]","[redness, skin imbalance]"
2,"[soothing, balancing]","[redness, skin imbalance]"
3,"[acne-free, pore-care, brightening, anti-aging]","[wrinkles, pigmentation, acne, enlarged pores]"
4,"[brightening, soothing]","[pigmentation, redness]"

In [23]:
newdf.head()

,product_name,product_type,brand,notable_effects,skintype,picture_src,skin_condition
0,ACWELL Bubble Free PH Balancing Cleanser,Face Wash,ACWELL,"[acne-free, pore-care, brightening, anti-aging]",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"[wrinkles, pigmentation, acne, enlarged pores]"
1,ACWELL pH Balancing Soothing Cleansing Foam,Face Wash,ACWELL,"[soothing, balancing]","Normal, Dry, Combination",https://images.soco.id/8f08ced0-344d-41f4-a15e...,"[redness, skin imbalance]"
2,Acwell Licorice pH Balancing Cleansing Toner,Toner,ACWELL,"[soothing, balancing]","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","[redness, skin imbalance]"
3,ACWELL Aquaseal Soothing Tonic,Toner,ACWELL,"[acne-free, pore-care, brightening, anti-aging]",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"[wrinkles, pigmentation, acne, enlarged pores]"
4,Licorice pH Balancing Essence Mist,Toner,ACWELL,"[brightening, soothing]","Normal, Dry","https://www.sociolla.com/cdn-cgi/image/w=425,f...","[pigmentation, redness]"

In [24]:
newdf.shape

(1224, 7)

In [26]:
df_for_nunique = newdf.copy()
df_for_nunique['notable_effects'] = df_for_nunique['notable_effects'].apply(tuple)
df_for_nunique['skin_condition'] = df_for_nunique['skin_condition'].apply(tuple)
display(df_for_nunique.nunique())

product_name       1192
product_type          5
brand               211
notable_effects     142
skintype             15
picture_src        1182
skin_condition      100
dtype: int64

In [27]:
df_for_nunique.head()

,product_name,product_type,brand,notable_effects,skintype,picture_src,skin_condition
0,ACWELL Bubble Free PH Balancing Cleanser,Face Wash,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, acne, enlarged pores)"
1,ACWELL pH Balancing Soothing Cleansing Foam,Face Wash,ACWELL,"(soothing, balancing)","Normal, Dry, Combination",https://images.soco.id/8f08ced0-344d-41f4-a15e...,"(redness, skin imbalance)"
2,Acwell Licorice pH Balancing Cleansing Toner,Toner,ACWELL,"(soothing, balancing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(redness, skin imbalance)"
3,ACWELL Aquaseal Soothing Tonic,Toner,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, acne, enlarged pores)"
4,Licorice pH Balancing Essence Mist,Toner,ACWELL,"(brightening, soothing)","Normal, Dry","https://www.sociolla.com/cdn-cgi/image/w=425,f...","(pigmentation, redness)"

In [28]:
df_for_nunique.head(20)

,product_name,product_type,brand,notable_effects,skintype,picture_src,skin_condition
0,ACWELL Bubble Free PH Balancing Cleanser,Face Wash,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, acne, enlarged pores)"
1,ACWELL pH Balancing Soothing Cleansing Foam,Face Wash,ACWELL,"(soothing, balancing)","Normal, Dry, Combination",https://images.soco.id/8f08ced0-344d-41f4-a15e...,"(redness, skin imbalance)"
2,Acwell Licorice pH Balancing Cleansing Toner,Toner,ACWELL,"(soothing, balancing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(redness, skin imbalance)"
3,ACWELL Aquaseal Soothing Tonic,Toner,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, acne, enlarged pores)"
4,Licorice pH Balancing Essence Mist,Toner,ACWELL,"(brightening, soothing)","Normal, Dry","https://www.sociolla.com/cdn-cgi/image/w=425,f...","(pigmentation, redness)"
5,Licorice pH Balancing Advance Serum,Serum,ACWELL,"(moisturizing, brightening, anti-aging)","Normal, Dry, Oily, Combination","https://www.sociolla.com/cdn-cgi/image/w=425,f...","(dry and dehydrated skin, pigmentation, wrinkles)"
6,Licorice pH Balancing Essential Cream,Moisturizer,ACWELL,"(moisturizing, brightening)","Normal, Dry, Oily, Combination, Sensitive","https://www.sociolla.com/cdn-cgi/image/w=244,f...","(dry and dehydrated skin, pigmentation)"
7,Real Aqua Balancing Cream,Moisturizer,ACWELL,"(hydrating, balancing, moisturizing)","Normal, Dry, Combination","https://www.sociolla.com/cdn-cgi/image/w=244,f...","(dry and dehydrated skin, skin imbalance)"
8,AHC Peony Bright Clearing Toner,Toner,AHC,"(pore-care, brightening, anti-aging)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, enlarged pores)"
9,AHC Hyaluronic Toner,Toner,AHC,"(anti-aging,)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles,)"
10,AHC Peony Bright Luminous Serum,Serum,AHC,"(brightening, anti-aging, uv-protection)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, sun damage)"
11,AIZEN SunOrion UV Sunscreen,Sunscreen,AIZEN,"(anti-aging, uv-protection)","Dry, Oily, Sensitive",https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, sun damage)"
12,AIZEN Incredipeel Exfoliating + Purifying Faci...,Toner,AIZEN,"(balancing, oil-control, pore-care)","Normal, Combination",https://www.beautyhaul.com/assets/uploads/prod...,"(skin imbalance, enlarged pores, oily skin)"
13,AIZEN Whitifique Face Cream,Moisturizer,AIZEN,"(brightening, anti-aging, uv-protection)",Oily,https://www.beautyhaul.com/assets/uploads/prod...,"(wrinkles, pigmentation, sun damage)"
14,ANESSA Whitening UV Sunscreen Gel,Sunscreen,ANESSA,"(hydrating, moisturizing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(dry and dehydrated skin,)"
15,ANESSA Perfect UV Sunscreen Skincare Spray,Sunscreen,ANESSA,"(hydrating, soothing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(dry and dehydrated skin, redness)"
16,ANESSA Moisture UV Sunscreen Mild Gel,Sunscreen,ANESSA,"(uv-protection, no-whitecast)","Dry, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(sun damage, sun protection)"
17,ANESSA Perfect UV Sunscreen Skincare Milk,Sunscreen,ANESSA,"(hydrating, soothing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(dry and dehydrated skin, redness)"
18,ANESSA Perfect UV Sunscreen Skincare Gel,Sunscreen,ANESSA,"(hydrating, moisturizing)","Normal, Dry, Oily, Combination, Sensitive","https://www.soco.id/cdn-cgi/image/w=73,format=...","(dry and dehydrated skin,)"
19,ANESSA Perfect UV Sunscreen Mild Milk,Sunscreen,ANESSA,"(skin-barrier, uv-protection)",Sensitive,"https://www.soco.id/cdn-cgi/image/w=73,format=...","(sun damage, impaired skin barrier)"

In [29]:
output_path = '/content/drive/MyDrive/ML/newdf_processed.csv'
newdf.to_csv(output_path, index=False)
print(f'DataFrame saved to {output_path}')

DataFrame saved to /content/drive/MyDrive/ML/newdf_processed.csv

In [30]:
df_for_nunique.columns

Index(['product_name', 'product_type', 'brand', 'notable_effects', 'skintype',
       'picture_src', 'skin_condition'],
      dtype='object')

In [31]:
rearranged_df = df_for_nunique[['skintype','skin_condition','product_type','product_name', 'brand', 'notable_effects', 'picture_src']]
display(rearranged_df.head())

,skintype,skin_condition,product_type,product_name,brand,notable_effects,picture_src
0,Oily,"(wrinkles, pigmentation, acne, enlarged pores)",Face Wash,ACWELL Bubble Free PH Balancing Cleanser,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",https://www.beautyhaul.com/assets/uploads/prod...
1,"Normal, Dry, Combination","(redness, skin imbalance)",Face Wash,ACWELL pH Balancing Soothing Cleansing Foam,ACWELL,"(soothing, balancing)",https://images.soco.id/8f08ced0-344d-41f4-a15e...
2,"Normal, Dry, Oily, Combination, Sensitive","(redness, skin imbalance)",Toner,Acwell Licorice pH Balancing Cleansing Toner,ACWELL,"(soothing, balancing)","https://www.soco.id/cdn-cgi/image/w=73,format=..."
3,Oily,"(wrinkles, pigmentation, acne, enlarged pores)",Toner,ACWELL Aquaseal Soothing Tonic,ACWELL,"(acne-free, pore-care, brightening, anti-aging)",https://www.beautyhaul.com/assets/uploads/prod...
4,"Normal, Dry","(pigmentation, redness)",Toner,Licorice pH Balancing Essence Mist,ACWELL,"(brightening, soothing)","https://www.sociolla.com/cdn-cgi/image/w=425,f..."

In [32]:
output_path = '/content/drive/MyDrive/ML/skin_recommendation_dataset.csv'
rearranged_df.to_csv(output_path, index=False)
print(f'DataFrame saved to {output_path}')

DataFrame saved to /content/drive/MyDrive/ML/skin_recommendation_dataset.csv